# .github/ISSUE_TEMPLATE/epic-requirement.yml
name: Epic Requirement
description: Propose a new requirement, that will hold granular requirements as children.
labels: [EPIC, REQ]
title: "REQ-"

body:
  - type: markdown
    attributes:
      value: |
        **Naming convention**
        Use `REQ-domain-subdomain-component`. Lowercase, hyphen-separated, unique.
        Examples:
        - `REQ-actor-components-health`
        - `REQ-procedure-firearm`

        **Add one tag**
        Add exactly one of these labels to this issue to indicate priority: `MUST`, `SHOULD`, `MAY`.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the requirement.
    validations:
      required: true