# .github/ISSUE_TEMPLATE/epic.yml
name: Granular Requirement
description: Propose a new requirement.
labels: [REQ]
title: "REQ-"

body:
  - type: markdown
    attributes:
      value: |
        **Naming convention**
        Use `REQ-domain-subdomain-component`. Lowercase, hyphen-separated, unique.
        Examples:
        - `REQ-actor-healthcomponent-001-overflow`
        - `REQ-procedure-firearm-001-fire`

        ** Add one of the following tags** 
        [MUST][MUST][MAY] to this issue, to indiciate priority.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the requirement.
    validations:
      required: true
