# .github/ISSUE_TEMPLATE/granular-requirement.yml
name: Granular Requirement
description: Propose a new granualr requirement.
labels: [REQ]
title: "REQ-"

body:
  - type: markdown
    attributes:
      value: |
        **Naming convention**
        Use `REQ-domain-subdomain-component`. Lowercase, hyphen-separated, unique.
        Examples:
        - `REQ-actor-component-health-001-overflow`
        - `REQ-actor-component-health-002-damagetrack`
        - `REQ-procedure-firearm-001-fire`

        **Add one tag**
        Add exactly one of these labels to this issue to indicate priority: `MUST`, `SHOULD`, `MAY`.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the requirement.
    validations:
      required: true
