# .github/ISSUE_TEMPLATE/requirement.yml
name: Requirement
description: Propose a new requirement.
labels: [REQ]
title: "REQ-domain-subdomain-component"

body:
  - type: markdown
    attributes:
      value: |
        **Naming convention**
        Use `REQ-domain-subdomain-component`. Lowercase, hyphen-separated, unique.
        Examples:
        - `REQ-actor-health-overflow`
        - `REQ-procedure-firearm-opposed`

  - type: dropdown
    id: type
    attributes:
      label: Type
      options: [MUST, SHOULD, MAY]
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One or two sentences describing the requirement.
    validations:
      required: true
