name: Create Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install tooling
        run: sudo apt-get update && sudo apt-get install -y jq zip

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      # If the latest pushed commit is the release commit, skip bumping
      - name: Determine bump type
        id: bump
        if: ${{ !contains(github.event.head_commit.message || '', 'chore(release)') }}
        run: |
          set -e
          TYPE="$(npx conventional-recommended-bump -p angular -r 0 || true)"
          TYPE="$(echo "$TYPE" | tr -d '\r\n' | xargs)"
          if [ -z "$TYPE" ]; then
            echo "No conventional commits since last tag. Skipping."
            echo "bump=" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          echo "BUMP_TYPE=$TYPE" >> "$GITHUB_ENV"
          echo "bump=$TYPE" >> "$GITHUB_OUTPUT"

      # Force-reset prerelease to alpha.0 by computing the next BASE version
      - name: Version bump + tag (alpha.0)
        if: steps.bump.outputs.bump != ''
        run: |
          set -e
          BASE="$(node -p "require('./package.json').version.split('-')[0]")"
          IFS='.' read -r MA MI PA <<< "$BASE"
          case "$BUMP_TYPE" in
            major) MA=$((MA+1)); MI=0; PA=0 ;;
            minor) MI=$((MI+1)); PA=0 ;;
            patch|*) PA=$((PA+1)) ;;
          esac
          NEXT_BASE="${MA}.${MI}.${PA}"
          npx standard-version --release-as "${NEXT_BASE}-alpha.0"
          git push --follow-tags origin HEAD:main

      - name: Read version
        id: v
        if: steps.bump.outputs.bump != ''
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Build manifests (latest + pinned)
        if: steps.v.outputs.VERSION != ''
        run: |
          set -e
          VERSION="${{ steps.v.outputs.VERSION }}"
          REPO="https://github.com/${GITHUB_REPOSITORY}"
          ZIP="sr3e-${VERSION}.zip"

          MANIFEST_PINNED="${REPO}/releases/download/v${VERSION}/system.json"
          MANIFEST_LATEST="${REPO}/releases/latest/download/system.json"
          DOWNLOAD_URL="${REPO}/releases/download/v${VERSION}/${ZIP}"

          jq --arg ver "$VERSION" --arg manifest "$MANIFEST_LATEST" --arg download "$DOWNLOAD_URL" \
             '.version=$ver | .manifest=$manifest | .download=$download' \
             system.json > system.latest.json

          jq --arg ver "$VERSION" --arg manifest "$MANIFEST_PINNED" --arg download "$DOWNLOAD_URL" \
             '.version=$ver | .manifest=$manifest | .download=$download' \
             system.json > system.pinned.json

      - name: Build
        if: steps.v.outputs.VERSION != ''
        run: npm run build

      - name: Create package (players only)
        if: steps.v.outputs.VERSION != ''
        run: |
          set -e
          VERSION="${{ steps.v.outputs.VERSION }}"
          ROOT="package/sr3e"
          mkdir -p "$ROOT"

          cp system.pinned.json "$ROOT/system.json"
          cp -r build "$ROOT/"
          cp -r lang "$ROOT/"
          [ -d themes ]    && cp -r themes "$ROOT/"
          [ -d textures ]  && cp -r textures "$ROOT/"
          [ -d fonts ]     && cp -r fonts "$ROOT/"
          [ -d styles ]    && cp -r styles "$ROOT/"
          [ -d licences ]  && cp -r licences "$ROOT/"
          [ -d licenses ]  && cp -r licenses "$ROOT/"
          [ -f README.md ] && cp README.md "$ROOT/"

          (cd package && zip -r "../sr3e-${VERSION}.zip" "sr3e")

          # prepare upload alias
          cp system.latest.json system.json

      - name: Write release body
        if: steps.v.outputs.VERSION != ''
        run: |
          echo "Install/Update manifest (latest channel): https://github.com/${GITHUB_REPOSITORY}/releases/latest/download/system.json" > RELEASE_BODY.md
          echo "Pinned manifest for this version: https://github.com/${GITHUB_REPOSITORY}/releases/download/v${{ steps.v.outputs.VERSION }}/system.json" >> RELEASE_BODY.md

      - name: Create GitHub Release
        if: steps.v.outputs.VERSION != ''
        uses: softprops/action-gh-release@v2
        with:
          body_path: RELEASE_BODY.md
          files: |
            sr3e-${{ steps.v.outputs.VERSION }}.zip
            system.json
            system.pinned.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
